from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .models import Wave, WorkloadAssessment


REQUIRED_SECTIONS = (
    "# Move Lab Evidence Request",
    "## Purpose",
    "## Requested Lab Scope",
    "## Workload Scope",
    "## Required Controls",
    "## Evidence To Capture",
    "## Closeout Commands",
    "## Stop Conditions",
)

REQUIRED_FRAGMENTS = (
    "non-production Nutanix Move appliance",
    "dry-run-only",
    "started_migrations=0",
    "redacted",
    "NMRCP_MOVE_LAB_ACK",
    "proof_scope=approved_lab_move_appliance",
    "nmrcp_move_lab_transcript_validation_v1",
    "generate-approved-move-lab-proof",
    "nmrcp_move_lab_proof_validation_v1",
    "nmrcp_move_lab_evidence_intake_v1",
    "validate-move-lab-proof",
    "validate-move-lab-evidence-intake",
    "--move-lab-evidence-intake",
)


@dataclass(frozen=True)
class MoveLabEvidenceRequestValidation:
    status: str
    checks: int
    errors: tuple[str, ...]
    warnings: tuple[str, ...]

    @property
    def ok(self) -> bool:
        return not self.errors

    def summary(self) -> str:
        return f"{self.status.upper()}: checks={self.checks}, errors={len(self.errors)}, warnings={len(self.warnings)}"


def write_move_lab_evidence_request(
    assessments: list[WorkloadAssessment],
    waves: list[Wave],
    path: Path,
) -> Path:
    included = [assessment for assessment in assessments if assessment.readiness == "ready"]
    held = [assessment for assessment in assessments if assessment.readiness != "ready"]
    wave_names = ", ".join(wave.name for wave in waves) or "No waves generated"
    owners = sorted({assessment.owner for assessment in assessments if assessment.owner and assessment.owner != "Unassigned"})
    lines = [
        "# Move Lab Evidence Request",
        "",
        "## Purpose",
        "",
        "Request an approved non-production Nutanix Move appliance proof window for the reviewed NMRCP dry-run payload.",
        "This request exists so partners, MSPs, and change boards can approve the final evidence capture without exposing secrets or production endpoints.",
        "",
        "## Requested Lab Scope",
        "",
        "- Environment: non-production Nutanix Move appliance.",
        "- Payload mode: dry-run-only.",
        "- Production targets: prohibited.",
        "- Migration starts: prohibited; require `started_migrations=0`.",
        "- Proof scope: `proof_scope=approved_lab_move_appliance`.",
        "- Local acknowledgement guard: `NMRCP_MOVE_LAB_ACK=I_UNDERSTAND_LAB_ONLY`.",
        "",
        "## Workload Scope",
        "",
        f"- Assessed workloads: `{len(assessments)}`.",
        f"- Workloads eligible for reviewed dry-run payload: `{len(included)}`.",
        f"- Held workloads excluded from Move submission: `{len(held)}`.",
        f"- Migration waves: `{wave_names}`.",
        f"- Workload owners represented: `{', '.join(owners) if owners else 'Unassigned only'}`.",
        "",
        "## Required Controls",
        "",
        "- Use lab-only Move, vCenter, Prism Central, networks, and workloads.",
        "- Submit only the reviewed dry-run payload generated by NMRCP.",
        "- Capture only relative API paths, HTTP methods, 2xx status codes, dry-run flags, mutation flags, redaction flags, and optional request/response hashes.",
        "- Do not store raw URLs, headers, request bodies, response bodies, cookies, tokens, passwords, authorization values, FQDNs, IP addresses, or customer identifiers.",
        "- Keep all evidence redacted before it leaves the lab operator workstation.",
        "",
        "## Evidence To Capture",
        "",
        "- `nmrcp_move_submit_readiness_v1` with `status=pass`.",
        "- Move lab capture-kit validation with `status=pass`.",
        "- `nmrcp_move_lab_transcript_validation_v1` with `status=pass`.",
        "- `nmrcp_move_lab_proof_validation_v1` with `status=pass` and approved lab scope.",
        "- `nmrcp_move_lab_evidence_intake_v1` with `status=pass`.",
        "",
        "## Closeout Commands",
        "",
        "Run these from the repository root after the approved lab capture files are redacted:",
        "",
        "```powershell",
        '$env:NMRCP_MOVE_LAB_ACK = "I_UNDERSTAND_LAB_ONLY"',
        "python -m nmrcp.cli validate-move-lab-transcript `",
        "  --transcript outputs\\move-lab-capture-kit\\move-lab-transcript.approved.json `",
        "  --payload outputs\\sample-assessment\\move-api-payload.lab.dry-run.json `",
        "  --review examples\\sample_move_submit_review.json `",
        "  --out outputs\\move-lab-transcript-validation.json",
        "",
        "python -m nmrcp.cli generate-approved-move-lab-proof `",
        "  --transcript outputs\\move-lab-capture-kit\\move-lab-transcript.approved.json `",
        "  --transcript-validation outputs\\move-lab-transcript-validation.json `",
        "  --payload outputs\\sample-assessment\\move-api-payload.lab.dry-run.json `",
        "  --review examples\\sample_move_submit_review.json `",
        "  --approved-by \"[LAB_APPROVER]\" `",
        "  --out outputs\\move-lab-proof.approved.json",
        "",
        "python -m nmrcp.cli validate-move-lab-proof `",
        "  --proof outputs\\move-lab-proof.approved.json `",
        "  --payload outputs\\sample-assessment\\move-api-payload.lab.dry-run.json `",
        "  --review examples\\sample_move_submit_review.json `",
        "  --transcript-validation outputs\\move-lab-transcript-validation.json `",
        "  --out outputs\\move-lab-proof-validation.json",
        "",
        "python -m nmrcp.cli validate-move-lab-evidence-intake `",
        "  --payload outputs\\sample-assessment\\move-api-payload.lab.dry-run.json `",
        "  --review examples\\sample_move_submit_review.json `",
        "  --transcript outputs\\move-lab-capture-kit\\move-lab-transcript.approved.json `",
        "  --transcript-validation outputs\\move-lab-transcript-validation.json `",
        "  --proof outputs\\move-lab-proof.approved.json `",
        "  --proof-validation outputs\\move-lab-proof-validation.json `",
        "  --capture-kit-validation outputs\\move-lab-capture-kit-validation.json `",
        "  --out outputs\\move-lab-evidence-intake.json",
        "",
        "python -m nmrcp.cli change-gate `",
        "  --dir outputs\\sample-assessment `",
        "  --move-lab-proof outputs\\move-lab-proof-validation.json `",
        "  --move-lab-evidence-intake outputs\\move-lab-evidence-intake.json",
        "Remove-Item Env:\\NMRCP_MOVE_LAB_ACK",
        "```",
        "",
        "## Stop Conditions",
        "",
        "- Stop if any endpoint, workload, or target is production.",
        "- Stop if the Move appliance starts a migration instead of accepting a dry-run plan.",
        "- Stop if any evidence file contains unredacted secrets, endpoints, customer identifiers, IP addresses, or FQDNs.",
        "- Stop if proof validation is not `status=pass` with `proof_scope=approved_lab_move_appliance`.",
        "- Stop if evidence intake is not `status=pass`.",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def validate_move_lab_evidence_request(path: Path) -> MoveLabEvidenceRequestValidation:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return MoveLabEvidenceRequestValidation("fail", 1, (f"{path}: could not read Move lab evidence request: {exc}",), ())

    errors: list[str] = []
    checks = 0
    for section in REQUIRED_SECTIONS:
        checks += 1
        if section not in text:
            errors.append(f"Move lab evidence request missing required section: {section}")
    for fragment in REQUIRED_FRAGMENTS:
        checks += 1
        if fragment not in text:
            errors.append(f"Move lab evidence request missing required proof request reference: {fragment}")

    checks += 1
    if "production" not in text.lower():
        errors.append("Move lab evidence request must include production stop conditions")
    checks += 1
    if "redact" not in text.lower() and "redacted" not in text.lower():
        errors.append("Move lab evidence request must include redaction controls")

    return MoveLabEvidenceRequestValidation("pass" if not errors else "fail", checks, tuple(errors), ())
