import json
import tempfile
import unittest
from pathlib import Path

from nmrcp import __version__
from nmrcp.evidence import preferred_target, write_assessment
from nmrcp.models import WorkloadAssessment
from nmrcp.redaction import redact_dict
from nmrcp.scoring import assess_inventory
from nmrcp.waves import plan_waves


class WavesAndEvidenceTests(unittest.TestCase):
    def test_preferred_target_chooses_lower_readiness_and_risk(self):
        ahv = WorkloadAssessment("vm-1", "app", "apps", "prepare", 30, "ahv")
        nc2 = WorkloadAssessment("vm-1", "app", "apps", "research", 15, "nc2")

        preferred, reason = preferred_target(ahv, nc2)

        self.assertEqual(preferred, "nc2")
        self.assertIn("lower readiness", reason)

    def test_redaction_removes_sensitive_source_values(self):
        payload = {
            "endpoint": "https://vcenter01.corp.local/sdk",
            "operator": "owner@example.com",
            "password": "secret-value",
            "ip": "10.20.30.40",
        }

        redacted = redact_dict(payload)

        self.assertEqual(redacted["password"], "[REDACTED_SECRET]")
        self.assertEqual(redacted["operator"], "[REDACTED_EMAIL]")
        self.assertEqual(redacted["ip"], "[REDACTED_IP]")
        self.assertIn("[REDACTED_URL]", redacted["endpoint"])

    def test_evidence_export_writes_expected_artifacts(self):
        inventory = json.loads(Path("examples/sample_inventory.json").read_text(encoding="utf-8"))
        assessments = assess_inventory(inventory)
        waves = plan_waves(assessments)

        with tempfile.TemporaryDirectory() as tmp:
            out_dir = Path(tmp)
            write_assessment(inventory, assessments, waves, out_dir)

            self.assertTrue((out_dir / "assessment.json").exists())
            assessment_json = json.loads((out_dir / "assessment.json").read_text(encoding="utf-8"))
            self.assertEqual(assessment_json["run_metadata"]["schema_version"], "nmrcp_run_metadata_v1")
            self.assertEqual(assessment_json["run_metadata"]["product_version"], __version__)
            self.assertEqual(assessment_json["run_metadata"]["workloads"], 3)
            self.assertEqual(assessment_json["run_metadata"]["secret_policy"], "credentials_not_serialized")
            self.assertEqual(assessment_json["run_metadata"]["mutation_policy"], "read_only_collection_write_intent_gated")
            self.assertIn("inventory_coverage", assessment_json)
            self.assertEqual(assessment_json["inventory_coverage"]["workloads"], 3)
            self.assertEqual(assessment_json["business_context"]["schema_version"], "nmrcp_business_context_v1")
            self.assertTrue(
                any(
                    item["workload_id"] == "vm-3030" and item["tier"] == "critical"
                    for item in assessment_json["business_context"]["workloads"]
                )
            )
            self.assertEqual(assessment_json["source"]["collection_audit"]["schema"], "nmrcp_collection_audit_v1")
            self.assertEqual(assessment_json["source"]["collection_audit"]["mutating_calls"], 0)
            self.assertNotIn("vcenter01.corp.local", json.dumps(assessment_json["source"]["collection_audit"]))
            self.assertTrue((out_dir / "migration-waves.csv").exists())
            self.assertTrue((out_dir / "wave-execution-calendar.csv").exists())
            self.assertTrue((out_dir / "partner-handoff-matrix.csv").exists())
            self.assertTrue((out_dir / "dependency-sequence.csv").exists())
            self.assertTrue((out_dir / "dependency-review.csv").exists())
            self.assertTrue((out_dir / "connectivity-checklist.csv").exists())
            self.assertTrue((out_dir / "identity-cutover-plan.csv").exists())
            self.assertTrue((out_dir / "compatibility-research.csv").exists())
            self.assertTrue((out_dir / "tools-driver-readiness.csv").exists())
            self.assertTrue((out_dir / "storage-posture.csv").exists())
            self.assertTrue((out_dir / "recovery-readiness.csv").exists())
            self.assertTrue((out_dir / "rollback-plan.csv").exists())
            self.assertTrue((out_dir / "move-staging-readiness.csv").exists())
            self.assertTrue((out_dir / "move-staging-brief.md").exists())
            self.assertTrue((out_dir / "workload-validation-checklist.csv").exists())
            self.assertTrue((out_dir / "migration-execution-queue.csv").exists())
            self.assertTrue((out_dir / "stakeholder-communication-plan.csv").exists())
            self.assertTrue((out_dir / "what-will-break-report.csv").exists())
            self.assertTrue((out_dir / "what-will-break-brief.md").exists())
            self.assertTrue((out_dir / "approval-exceptions.csv").exists())
            self.assertTrue((out_dir / "move-lab-closure-checklist.md").exists())
            self.assertTrue((out_dir / "move-lab-evidence-request.md").exists())
            self.assertTrue((out_dir / "source-endpoint-evidence-request.md").exists())
            coverage = (out_dir / "inventory-coverage.csv").read_text(encoding="utf-8")
            self.assertIn("coverage_percent", coverage)
            self.assertIn("vendor_support", coverage)
            self.assertIn("guest_identity", coverage)
            self.assertIn("application_owner_approval", coverage)
            self.assertIn("rollback_owner", coverage)
            manifest = json.loads((out_dir / "evidence-manifest.json").read_text(encoding="utf-8"))
            artifact_names = {artifact["name"] for artifact in manifest["artifacts"]}
            self.assertEqual(manifest["schema_version"], "nmrcp_evidence_manifest_v1")
            self.assertIn("inventory-coverage.csv", artifact_names)
            self.assertIn("wave-readiness-summary.csv", artifact_names)
            self.assertIn("wave-execution-calendar.csv", artifact_names)
            self.assertIn("partner-handoff-matrix.csv", artifact_names)
            self.assertIn("target-readiness-comparison.csv", artifact_names)
            self.assertIn("dependency-review.csv", artifact_names)
            self.assertIn("connectivity-checklist.csv", artifact_names)
            self.assertIn("identity-cutover-plan.csv", artifact_names)
            self.assertIn("compatibility-research.csv", artifact_names)
            self.assertIn("tools-driver-readiness.csv", artifact_names)
            self.assertIn("storage-posture.csv", artifact_names)
            self.assertIn("recovery-readiness.csv", artifact_names)
            self.assertIn("rollback-plan.csv", artifact_names)
            self.assertIn("move-staging-readiness.csv", artifact_names)
            self.assertIn("move-staging-brief.md", artifact_names)
            self.assertIn("prism-category-mapping.csv", artifact_names)
            self.assertIn("stakeholder-communication-plan.csv", artifact_names)
            self.assertIn("what-will-break-report.csv", artifact_names)
            self.assertIn("what-will-break-brief.md", artifact_names)
            self.assertIn("move-plan-brief.md", artifact_names)
            self.assertIn("migration-runbook.md", artifact_names)
            self.assertIn("operator-portal.html", artifact_names)
            self.assertIn("operator-report.html", artifact_names)
            self.assertIn("operator-dashboard.html", artifact_names)
            self.assertIn("pre-post-validation-checklist.md", artifact_names)
            self.assertIn("move-lab-closure-checklist.md", artifact_names)
            self.assertIn("move-lab-evidence-request.md", artifact_names)
            self.assertIn("source-endpoint-evidence-request.md", artifact_names)
            self.assertIn("workload-validation-checklist.csv", artifact_names)
            self.assertIn("migration-execution-queue.csv", artifact_names)
            self.assertIn("remediation-tracker.csv", artifact_names)
            self.assertIn("migration-risk-register.csv", artifact_names)
            self.assertIn("owner-risk-summary.csv", artifact_names)
            self.assertIn("business-impact-summary.csv", artifact_names)
            self.assertIn("owner-signoff-matrix.csv", artifact_names)
            self.assertIn("approval-exceptions.csv", artifact_names)
            self.assertIn("executive-readiness-brief.md", artifact_names)
            self.assertTrue(all(len(artifact["sha256"]) == 64 for artifact in manifest["artifacts"]))
            tracker = (out_dir / "remediation-tracker.csv").read_text(encoding="utf-8")
            self.assertIn("status,owner,wave,workload_id", tracker)
            self.assertIn("open,Business Apps", tracker)
            self.assertIn("snapshot_age_exceeds_policy", tracker)
            self.assertIn("Install or validate Nutanix VirtIO drivers before cutover.", tracker)
            driver_readiness = (out_dir / "tools-driver-readiness.csv").read_text(encoding="utf-8")
            self.assertIn("schema_version,workload_id,name,owner,target,readiness,vmware_tools", driver_readiness)
            self.assertIn("vm-2020,erp-app-01,Business Apps,ahv,blocked,true,unknown,false,remediate,virtio_not_ready", driver_readiness)
            storage_posture = (out_dir / "storage-posture.csv").read_text(encoding="utf-8")
            self.assertIn("schema_version,workload_id,name,owner,target,readiness,disk_count", storage_posture)
            self.assertIn("vm-1001,pilot-web-01,Platform Team,ahv,ready,1,120,true,false,false,false,false,ds-pilot,38,ready", storage_posture)
            recovery_readiness = (out_dir / "recovery-readiness.csv").read_text(encoding="utf-8")
            self.assertIn("schema_version,workload_id,name,owner,target,readiness,backup_protected", recovery_readiness)
            self.assertIn("vm-2020,erp-app-01,Business Apps,ahv,blocked,true,4,2,17", recovery_readiness)
            staging_readiness = (out_dir / "move-staging-readiness.csv").read_text(encoding="utf-8")
            self.assertIn("stage_status", staging_readiness)
            self.assertIn("vm-1001,pilot-web-01,Platform Team,ahv,Wave 0 - Pilot Ready,include,ready,0,ready,ready,ready,not supplied,not confirmed,hold", staging_readiness)
            self.assertIn("vm-3030,payments-edge-01,Payments,ahv,Excluded Until Cleared,hold,blocked", staging_readiness)
            move_staging_brief = (out_dir / "move-staging-brief.md").read_text(encoding="utf-8")
            self.assertIn("# Move Staging Brief", move_staging_brief)
            self.assertIn("Decision signal: Hold blocked workloads out of Nutanix Move", move_staging_brief)
            self.assertIn("## Holds And Conditional Reviews", move_staging_brief)
            self.assertIn("payments-edge-01", move_staging_brief)
            workload_validation = (out_dir / "workload-validation-checklist.csv").read_text(encoding="utf-8")
            self.assertIn("schema_version,workload_id,name,owner,target,wave,move_plan_decision,stage_status,validation_phase", workload_validation)
            self.assertIn("vm-1001,pilot-web-01,Platform Team,ahv,Wave 0 - Pilot Ready,include,hold,pre_migration,owner_and_rollback_approval", workload_validation)
            self.assertIn("vm-3030,payments-edge-01,Payments,ahv,Excluded Until Cleared,hold,hold,cutover,move_execution_guard", workload_validation)
            execution_queue = (out_dir / "migration-execution-queue.csv").read_text(encoding="utf-8")
            self.assertIn("schema_version,execution_order,workload_id,name,owner,target,wave", execution_queue)
            prism_categories = (out_dir / "prism-category-mapping.csv").read_text(encoding="utf-8")
            self.assertIn("schema_version,workload_id,name,owner,tier,readiness,source_tags,category_assignments", prism_categories)
            self.assertIn("NMRCP:Owner=Platform_Team", prism_categories)
            stakeholder_plan = (out_dir / "stakeholder-communication-plan.csv").read_text(encoding="utf-8")
            self.assertIn("schema_version,owner,wave,audience,workload_ids,workload_names", stakeholder_plan)
            self.assertIn("ready_owner_signoff", stakeholder_plan)
            self.assertIn("blocked_owner_review", stakeholder_plan)
            what_will_break = (out_dir / "what-will-break-report.csv").read_text(encoding="utf-8")
            self.assertIn("schema_version,workload_id,name,owner,target,wave,readiness,risk_score,finding_code", what_will_break)
            self.assertIn("no_open_readiness_breakage", what_will_break)
            self.assertIn("do_not_schedule", what_will_break)
            what_will_break_brief = (out_dir / "what-will-break-brief.md").read_text(encoding="utf-8")
            self.assertIn("# What Will Break Brief", what_will_break_brief)
            self.assertIn("Decision signal: Hold blocked workloads out of Nutanix Move", what_will_break_brief)
            self.assertIn("[critical] payments-edge-01 (`vm-3030`)", what_will_break_brief)
            self.assertIn("Owner `Payments`, wave `Excluded Until Cleared`", what_will_break_brief)
            self.assertIn("vm-3030,payments-edge-01,Payments,ahv,Excluded Until Cleared,hold,hold,blocked", execution_queue)
            dependency_review = (out_dir / "dependency-review.csv").read_text(encoding="utf-8")
            self.assertIn("schema_version,row_type,source_workload_id,source_name,source_owner,target", dependency_review)
            self.assertIn("vm-3030,payments-edge-01,Payments,ahv,blocked,external-hsm", dependency_review)
            risk_register = (out_dir / "migration-risk-register.csv").read_text(encoding="utf-8")
            self.assertIn("finding_code,highest_severity,affected_workloads", risk_register)
            self.assertIn("nsx_dependency,critical,1,0,0,0,1,100,Payments,Excluded Until Cleared,payments-edge-01,yes", risk_register)
            self.assertIn("vds_mapping_required,medium,2,0,0,0,2,100,Business Apps;Payments", risk_register)
            wave_summary = (out_dir / "wave-readiness-summary.csv").read_text(encoding="utf-8")
            self.assertIn("wave,description,total_workloads,ready,research,prepare,blocked", wave_summary)
            self.assertIn("Wave 0 - Pilot Ready,", wave_summary)
            self.assertIn("Wave 0 - Pilot Ready,Low-risk workloads that can validate the migration factory and rollback evidence.,1,1,0,0,0,0.0,0,0,0,0,ready,pilot-web-01,,Platform Team", wave_summary)
            self.assertIn("Excluded Until Cleared,", wave_summary)
            self.assertIn("2,0,0,0,2,90.0,100,12,1,6,hold,,erp-app-01;payments-edge-01,Business Apps;Payments", wave_summary)
            self.assertIn("Clear blocked findings and obtain formal risk acceptance before Move staging.", wave_summary)
            wave_calendar = (out_dir / "wave-execution-calendar.csv").read_text(encoding="utf-8")
            self.assertIn("schema_version,execution_sequence,wave,window_type,move_staging_status", wave_calendar)
            self.assertIn("pilot_or_standard_move_window,ready", wave_calendar)
            self.assertIn("blocked_no_move_window,hold", wave_calendar)
            partner_handoff = (out_dir / "partner-handoff-matrix.csv").read_text(encoding="utf-8")
            self.assertIn("schema_version,role,handoff_scope,owned_artifacts", partner_handoff)
            self.assertIn("migration_lead", partner_handoff)
            self.assertIn("move_operator", partner_handoff)
            owner_summary = (out_dir / "owner-risk-summary.csv").read_text(encoding="utf-8")
            self.assertIn("owner,total_workloads,ready,research,prepare,blocked", owner_summary)
            self.assertIn("Business Apps,1,0,0,0,1,80.0,80,5,0,3,2,erp-app-01", owner_summary)
            self.assertIn("Clear blocked workload findings before Move staging.", owner_summary)
            business_summary = (out_dir / "business-impact-summary.csv").read_text(encoding="utf-8")
            self.assertIn("tier,total_workloads,ready,research,prepare,blocked", business_summary)
            self.assertIn("critical,2,0,0,0,2,90.0,100,12,1,6,blocked,Business Apps;Payments,erp-app-01;payments-edge-01", business_summary)
            self.assertIn("critical tier has blocked workloads; clear erp-app-01, payments-edge-01 before executive migration approval.", business_summary)
            self.assertIn("noncritical,1,1,0,0,0,0.0,0,0,0,0,ready,Platform Team,,Wave 0 - Pilot Ready", business_summary)
            signoff = (out_dir / "owner-signoff-matrix.csv").read_text(encoding="utf-8")
            self.assertIn("status,owner,wave,workload_id", signoff)
            self.assertIn("pending,Business Apps,Excluded Until Cleared,vm-2020", signoff)
            self.assertIn("application_owner;dependency_owner;migration_lead;network_owner;risk_acceptance;rollback_owner", signoff)
            self.assertIn("blocked workload requires remediation and formal risk acceptance", signoff)
            self.assertIn("before remediation closure", signoff)
            approval_exceptions = (out_dir / "approval-exceptions.csv").read_text(encoding="utf-8")
            self.assertIn("schema_version,exception_id,workload_id,name,owner,target,wave", approval_exceptions)
            self.assertIn("vm-3030:high_risk_exception:risk_score_threshold,vm-3030,payments-edge-01,Payments,ahv,Excluded Until Cleared,blocked,100,high_risk_exception,risk_score_threshold,critical", approval_exceptions)
            comparison = (out_dir / "target-readiness-comparison.csv").read_text(encoding="utf-8")
            self.assertIn("ahv_readiness", comparison)
            self.assertIn("nc2_readiness", comparison)
            self.assertIn("preferred_target", comparison)
            self.assertIn("vendor_support_unconfirmed", comparison)
            compatibility_research = (out_dir / "compatibility-research.csv").read_text(encoding="utf-8")
            self.assertIn("schema_version,workload_id,name,owner,target,readiness,tier,guest_os", compatibility_research)
            self.assertIn("vm-3030,payments-edge-01,Payments,ahv,blocked,critical", compatibility_research)
            report = (out_dir / "operator-report.html").read_text(encoding="utf-8")
            self.assertIn("Nutanix Migration Readiness Operator Report", report)
            self.assertIn("Collection Audit Proof", report)
            self.assertIn("nmrcp_collection_audit_v1", report)
            self.assertIn("/api/vcenter/vm/{vm}", report)
            self.assertIn("Mutating calls", report)
            self.assertIn("[REDACTED_URL]", report)
            self.assertNotIn("vcenter01.corp.local", report)
            dashboard = (out_dir / "operator-dashboard.html").read_text(encoding="utf-8")
            self.assertIn("Nutanix Migration Readiness Dashboard", dashboard)
            self.assertIn("nmrcp_operator_dashboard_v1", dashboard)
            self.assertIn("Operator Work Queue", dashboard)
            self.assertIn("Do not stage prepare or blocked workloads in Nutanix Move.", dashboard)
            self.assertIn("snapshot_age_exceeds_policy", dashboard)
            self.assertIn("hold until remediated", dashboard)
            self.assertNotIn("vcenter01.corp.local", dashboard)
            move_plan = (out_dir / "nutanix-move-plan.csv").read_text(encoding="utf-8")
            self.assertIn("include_in_move_plan", move_plan)
            self.assertIn("hold_until_remediated", move_plan)
            evidence = (out_dir / "change-board-evidence.md").read_text(encoding="utf-8")
            self.assertIn("# Change Board Evidence", evidence)
            self.assertIn("## Collection Audit Proof", evidence)
            self.assertIn("Read-only API paths", evidence)
            self.assertIn("Mutating calls: `0`", evidence)
            self.assertIn("[REDACTED", evidence)
            executive_brief = (out_dir / "executive-readiness-brief.md").read_text(encoding="utf-8")
            self.assertIn("# Executive Readiness Brief", executive_brief)
            self.assertIn("Recommended decision: Do not approve broad Move staging", executive_brief)
            self.assertIn("Move staging candidates: 1", executive_brief)
            self.assertIn("- critical: 2 workloads, status `blocked`, held `erp-app-01; payments-edge-01`.", executive_brief)
            self.assertIn("- Wave 0 - Pilot Ready: 1 workloads, staging `ready`, held `none`.", executive_brief)
            self.assertIn("[critical] nsx_dependency on payments-edge-01", executive_brief)
            self.assertIn("Approved Nutanix Move lab appliance proof is supplied", executive_brief)
            runbook = (out_dir / "migration-runbook.md").read_text(encoding="utf-8")
            self.assertIn("# Migration Runbook", runbook)
            self.assertIn("Universal Stop Conditions", runbook)
            self.assertIn("operator-dashboard.html", runbook)
            self.assertIn("wave-readiness-summary.csv", runbook)
            self.assertIn("migration-risk-register.csv", runbook)
            self.assertIn("business-impact-summary.csv", runbook)
            self.assertIn("move-staging-brief.md", runbook)
            self.assertIn("what-will-break-brief.md", runbook)
            self.assertIn("executive-readiness-brief.md", runbook)
            self.assertIn("move-lab-closure-checklist.md", runbook)
            self.assertIn("move-lab-evidence-request.md", runbook)
            self.assertIn("source-endpoint-evidence-request.md", runbook)
            self.assertIn("hold until remediated", runbook)
            self.assertIn("Do not stage this workload in Nutanix Move", runbook)
            self.assertIn("snapshot_age_exceeds_policy", runbook)
            self.assertIn("Application owner approval: not supplied", runbook)
            self.assertIn("Rollback owner: not confirmed", runbook)
            self.assertIn("Dependency coordination:", runbook)
            self.assertIn("name=erp-db-01; type=unspecified; owner=Database Team; criticality=unspecified", runbook)
            self.assertIn("name=external-hsm; type=unspecified; owner=not assigned; criticality=unspecified", runbook)
            move_lab_closure = (out_dir / "move-lab-closure-checklist.md").read_text(encoding="utf-8")
            self.assertIn("# Move Lab Closure Checklist", move_lab_closure)
            self.assertIn("nmrcp_move_lab_evidence_intake_v1", move_lab_closure)
            self.assertIn("proof_scope=approved_lab_move_appliance", move_lab_closure)
            self.assertIn("--move-lab-evidence-intake", move_lab_closure)


if __name__ == "__main__":
    unittest.main()
